site_name: "DiffRoute Documentation"
site_description: "Technical reference and quickstart guides for diffroute."
theme:
  name: material
  logo: diffhydro.png
  features:
    - content.code.copy
extra_css:
  - stylesheets/extra.css
nav:
  - Overview: index.md
  - Quickstart: quickstart.md
  - Concepts:
      - Single Stage Routing: concepts/single_stage.md
      - Multi-stage Routing: concepts/multi_stage.md
      - Data Structures: concepts/data_structures.md
      - IO: concepts/io.md
  - Code Structure: code_structure.md
  - Examples:
      - Overview: examples/index.md
      - Routing a RAPID Project: examples/rapid.md
      - Defining a Custom IRF: examples/custom_irf.md
plugins:
  - search
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
